PatronManager/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PatronManager/main/default/objects/City__c/fields/Max_temp__c.field-meta.xml
<CustomField>
    <fullName>Max_temp__c</fullName>
    <label>Max temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Min_temp__c.field-meta.xml
<CustomField>
    <fullName>Min_temp__c</fullName>
    <label>Min temp</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Predictability__c.field-meta.xml
<CustomField>
    <fullName>Predictability__c</fullName>
    <label>Predictability</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/The_temp__c.field-meta.xml
<CustomField>
    <fullName>The_temp__c</fullName>
    <label>The temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Weather_state_name__c.field-meta.xml
<CustomField>
    <fullName>Weather_state_name__c</fullName>
    <label>Weather state name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/woeid__c.field-meta.xml
<CustomField>
    <fullName>woeid__c</fullName>
    <label>WhereInTheWorldId</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/classes/PatronManagerContainerControllerTest.cls
@isTest
public class PatronManagerContainerControllerTest {

    @isTest static void testSaveSearchedCity(){
		WeatherForecastCallout.MetaWeatherObject metaObject = new WeatherForecastCallout.MetaWeatherObject();
        metaObject.woeid = 2459115; 
        metaObject.title = 'New York';
        metaObject.weather_state_name = 'Clear';
        metaObject.min_temp ='13';
        metaObject.max_temp ='25';
        metaObject.the_temp ='22';
        metaObject.predictability ='65';
        
        Test.startTest();
        PatronManagerContainerController.saveSearchedCity(metaObject);
        Test.stopTest();
        
        List<City__c> queriedCity = PatronManagerContainerController.getCities();
        
        System.assertEquals(metaObject.title, queriedCity[0].Name);
        System.assertEquals(convertToFarenheit(metaObject.the_temp), queriedCity[0].The_temp__c);
        System.assertEquals(convertToFarenheit(metaObject.min_temp), queriedCity[0].Min_temp__c);
        System.assertEquals(metaObject.predictability, String.valueOf(queriedCity[0].Predictability__c));
        System.assertEquals(convertToFarenheit(metaObject.max_temp), queriedCity[0].Max_temp__c);
        System.assertEquals(metaObject.weather_state_name, queriedCity[0].Weather_state_name__c);
        System.assertEquals(metaObject.woeid, queriedCity[0].Woeid__c);
        
    }
    
    private static Decimal convertToFarenheit(String celciusNum){
        return Decimal.valueOf(celciusNum)*1.8+32;
    }
}