PatronManager/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PatronManager/main/default/objects/City__c/fields/Max_temp__c.field-meta.xml
<CustomField>
    <fullName>Max_temp__c</fullName>
    <label>Max temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Min_temp__c.field-meta.xml
<CustomField>
    <fullName>Min_temp__c</fullName>
    <label>Min temp</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Predictability__c.field-meta.xml
<CustomField>
    <fullName>Predictability__c</fullName>
    <label>Predictability</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/The_temp__c.field-meta.xml
<CustomField>
    <fullName>The_temp__c</fullName>
    <label>The temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Weather_state_name__c.field-meta.xml
<CustomField>
    <fullName>Weather_state_name__c</fullName>
    <label>Weather state name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/woeid__c.field-meta.xml
<CustomField>
    <fullName>woeid__c</fullName>
    <label>WhereInTheWorldId</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/classes/PatronManagerContainerController.cls
/*
 * Description: this class is the controller in the PatronManagerContainer aura component.
 */ 
public class PatronManagerContainerController {
    
    /*
     * Description: this method is used in the PatronManagerContaner aura cmp. It is used in the init method
     * to retrive all existing City__c records.
     */ 
    @AuraEnabled
    public static List<City__c> getCities(){
        return [Select Id, Name, The_temp__c, Min_temp__c,woeid__c, Max_temp__c, Weather_state_name__c, Predictability__c, Last_Sync__c
               From City__c Order By Name ASC];
        
    }

    /*
    * Description: this method is used for passing the searched key term, 
    * to the outbound weather callout class, from the PatronManagerContainer aura cmp.
    */
    @AuraEnabled
    public static void searchCity(String keyTerm){
        String formattedKeyTerm = keyTerm.trim();
        WeatherForecastCallout weatherForcastCallout = new WeatherForecastCallout();
        WeatherForecastCallout.MetaWeatherObject calloutResponse = weatherForcastCallout.getWeatherForecastForNewCity(formattedKeyTerm);
        saveSearchedCity(calloutResponse);
    }

    /*
    * Description: this method is used for saving a new searched city to the database, at the same time it converts 
    * celcius degrees results to farenheit degrees
    */
    @TestVisible
    private static void saveSearchedCity(WeatherForecastCallout.MetaWeatherObject newCity){
        City__c cityToInsert = new City__c(Name = newCity.title,
                                    Max_temp__c = Decimal.valueOf(newCity.max_temp)*1.8+32,
                                    Min_temp__c = Decimal.valueOf(newCity.min_temp)*1.8+32,
                                    Last_Sync__c = DateTime.now(),
                                    Predictability__c = Decimal.valueOf(newCity.predictability),
                                    The_temp__c = Decimal.valueOf(newCity.the_temp)*1.8+32,
                                    Weather_state_name__c = newCity.weather_state_name,
                                    woeid__c = newCity.woeid);
        try{
            insert cityToInsert;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

}