PatronManager/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PatronManager/main/default/objects/City__c/fields/Max_temp__c.field-meta.xml
<CustomField>
    <fullName>Max_temp__c</fullName>
    <label>Max temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Min_temp__c.field-meta.xml
<CustomField>
    <fullName>Min_temp__c</fullName>
    <label>Min temp</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Predictability__c.field-meta.xml
<CustomField>
    <fullName>Predictability__c</fullName>
    <label>Predictability</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/The_temp__c.field-meta.xml
<CustomField>
    <fullName>The_temp__c</fullName>
    <label>The temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/Weather_state_name__c.field-meta.xml
<CustomField>
    <fullName>Weather_state_name__c</fullName>
    <label>Weather state name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PatronManager/main/default/objects/City__c/fields/woeid__c.field-meta.xml
<CustomField>
    <fullName>woeid__c</fullName>
    <label>WhereInTheWorldId</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PatronManager/main/default/classes/WeatherForcastCalloutTest.cls
@isTest
public class WeatherForcastCalloutTest {
	
    @testSetup static void cityData(){
        City__c newYork = new City__c(Name = 'New York',
                                    Max_temp__c = 75,
                                    Min_temp__c = 44,
                                    Last_Sync__c = DateTime.now(),
                                    Predictability__c = 66,
                                    The_temp__c = 70,
                                    Weather_state_name__c = 'Clear',
                                    woeid__c = 2459115);
        insert newYork;
    }
    
    @isTest static void testGetWeatherForecastForAllCities(){
        List<City__c> newYorkCity = [Select Id, Name, Max_temp__c From City__c];
        List<City__c> retrievedCities;
        Test.startTest();
        WeatherForecastCallout weatherCallout = new WeatherForecastCallout();
        retrievedCities = weatherCallout.getWeatherForecastForAllCities();
        Test.stopTest();
 
        
        System.assertEquals(newYorkCity[0].Name, retrievedCities[0].Name);
    }
}